# Generated by Django 2.2.10 on 2020-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201012_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='static',
            name='hotline',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
