# Generated by Django 2.2.10 on 2020-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productofcustomer_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofcustomer',
            name='address_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
