# Generated by Django 2.2.10 on 2020-10-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customer_tax_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
