# Generated by Django 2.2.10 on 2020-10-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contract_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofcustomer',
            name='system_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
