# Generated by Django 2.2.10 on 2020-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productofcustomer_system_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productofcustomer',
            name='expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
