# Generated by Django 2.2.10 on 2020-10-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_productofcustomer_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
