# Generated by Django 2.2.10 on 2020-10-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201014_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
