# Generated by Django 2.2.10 on 2020-10-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201020_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='system_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productofcustomer',
            name='system_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='system_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
