# Generated by Django 2.2.10 on 2020-10-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20201020_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
