# Generated by Django 2.2.10 on 2020-10-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
