# Generated by Django 2.2.10 on 2020-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='static',
            name='contract_name',
        ),
    ]
