# Generated by Django 2.2.10 on 2020-10-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_static_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
