# Generated by Django 2.2.10 on 2020-10-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20201027_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='static',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='static',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='static',
            name='tax_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
