# Generated by Django 2.2.10 on 2020-10-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201027_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='static',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='static',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='static',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='static',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
