# Generated by Django 2.2.10 on 2020-10-27 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20201027_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='twitter',
        ),
    ]
