# Generated by Django 2.2.10 on 2020-10-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20201027_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
