# Generated by Django 2.2.10 on 2020-10-28 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_account_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
