from django.urls import path
from django.conf.urls import include
from api import views

urlpatterns = [
    path('admin/', include('api.supper_admin.urls')),
    path('account/create/', views.CreateAccountView.as_view()),
    path('account/login/', views.login),
    path('account/logout/', views.logout),
    path('account/change-password/',
         views.ChangePasswordView.as_view(), name='change-password'),
    path('account/request-reset-email/',
         views.RequestPasswordResetEmail.as_view(), name='request-reset-email'),
    path('account/password-reset-complete/',
         views.SetNewPasswordResetEmail.as_view(), name='password-reset-complete'),

    path('profile/',
         views.UserProfileView.as_view(), name='list-profile'),
    path('static/', views.StaticInfoView.as_view()),
    path('static/edit/', views.EditStaticInfoView.as_view()),
    path('products/', views.ListProductView.as_view()),
    path('products/<int:product_id>/', views.DetailProductView.as_view()), path('product-of-customer/<int:customer_id>/',
                                                                                views.GetProductOfCustomer.as_view()),
    path('contract/', views.ListContractCustomerView.as_view()),
    path('contract/<int:contract_id>/',
         views.DetailContractCustomerView.as_view()),
    path('customer/', views.DetailCustomerView.as_view()),
    path('order/', views.ListOrderView.as_view()),
    path('order/<int:order_id>/', views.DetailOrderView.as_view()),
    path('order/create/', views.CreateOrderView.as_view()),
    path('package/', views.ListPackageView.as_view()),
    path('package/product/<int:product_id>/',
         views.DetailPackageOfProductView.as_view()),
    path('package/<int:package_id>/', views.DetailPackageView.as_view()),
    path('homepage/package_of_customer/',
         views.HomePageListPackageOfCustomerCView.as_view()),
    path('homepage/count_package_of_customer/',
         views.HomePageCountPackageOfCustomerCView.as_view()),
    path('homepage/count_ticket/',
         views.HomePageListTicketCView.as_view()),
    path('homepage/count-alert-of-customer/',
         views.HomePageCountAlertCTView.as_view()),
    path('homepage/package-of-customer/<product_id>/',
         views.HomePageListCustomerOfProductSAView.as_view()),
    path('homepage/balance/', views.HomePageListBalanceOfCustomerCTView.as_view()),
    path('alert/', views.ListAlertCustomerView.as_view()),
    path('alert/<int:alert_id>/', views.DetailAlertCustomerView.as_view()),
    path('billing/', views.ListBillingCustomerView.as_view()),
    path('billing/<int:billing_id>/', views.DetailBillingCustomerView.as_view()),
    path('fcm-token/', views.UpdateFcmTokenView.as_view()),

]
